-- =============================================================================
-- Seed: Inventario de accesorios (plantilla importada)
-- Tablas afectadas: accesorios_subcategorias, accesorios_marcas,
--                   accesorios_colores, inv_accesorios
--
-- IMPORTANTE: Cambia v_tenant_id al ID de tu tenant antes de ejecutar.
-- =============================================================================

DO $$
DECLARE
  v_tenant_id bigint := 1;  -- << CAMBIA ESTE VALOR AL ID DE TU TENANT
BEGIN

  -- -----------------------------------------------------------------------
  -- 1. Subcategorias
  -- -----------------------------------------------------------------------
  INSERT INTO public.subcategorias (tenant_id, nombre) VALUES
    (v_tenant_id, 'ACCESORIO OEM'),
    (v_tenant_id, 'ACCESORIO GENERICO'),
    (v_tenant_id, 'TARJETA SIM'),
    (v_tenant_id, 'ESIM DIGITAL'),
    (v_tenant_id, 'MEMORIA DE ALMACENAMIENTO'),
    (v_tenant_id, 'LIBERADOR IPHONE'),
    (v_tenant_id, 'VIDRIO TEMPLADO BASICO'),
    (v_tenant_id, 'VIDRIO TEMPLADO 9D'),
    (v_tenant_id, 'VIDRIO TEMPLADO PRIVACIDAD'),
    (v_tenant_id, 'LAMINA DE HIDROGEL'),
    (v_tenant_id, 'CELULAR DE USO')
  ON CONFLICT (tenant_id, nombre) DO NOTHING;

  -- -----------------------------------------------------------------------
  -- 2. Marcas
  -- -----------------------------------------------------------------------
  INSERT INTO public.marcas (tenant_id, nombre) VALUES
    (v_tenant_id, 'APPLE'),
    (v_tenant_id, 'TELCEL'),
    (v_tenant_id, 'TELCEL QR'),
    (v_tenant_id, 'UNEFON'),
    (v_tenant_id, 'UNEFON QR'),
    (v_tenant_id, 'AT&T'),
    (v_tenant_id, 'AT&T QR'),
    (v_tenant_id, 'BIENESTAR'),
    (v_tenant_id, 'BAIT'),
    (v_tenant_id, 'BAIT QR'),
    (v_tenant_id, 'MOVISTAR'),
    (v_tenant_id, 'MOVISTAR QR'),
    (v_tenant_id, 'HUAWEI'),
    (v_tenant_id, 'KINGSTON'),
    (v_tenant_id, 'ADATA'),
    (v_tenant_id, 'LENOVO'),
    (v_tenant_id, 'LG'),
    (v_tenant_id, 'MOBO'),
    (v_tenant_id, 'MOREKA'),
    (v_tenant_id, 'MOTOROLA'),
    (v_tenant_id, 'OPPO'),
    (v_tenant_id, 'REALFIT'),
    (v_tenant_id, 'SAMSUNG'),
    (v_tenant_id, 'TWS F9'),
    (v_tenant_id, 'VARIOS'),
    (v_tenant_id, 'LECTOR CLIP'),
    (v_tenant_id, 'XIAOMI'),
    (v_tenant_id, '1HORA'),
    (v_tenant_id, 'USIM'),
    (v_tenant_id, 'HEIDCARD'),
    (v_tenant_id, 'DRAGON'),
    (v_tenant_id, 'GENGXIN'),
    (v_tenant_id, 'ZTE')
  ON CONFLICT (tenant_id, nombre) DO NOTHING;

  -- -----------------------------------------------------------------------
  -- 3. Colores
  -- -----------------------------------------------------------------------
  INSERT INTO public.colores (tenant_id, nombre) VALUES
    (v_tenant_id, 'SIN COLOR'),
    (v_tenant_id, 'BLANCO'),
    (v_tenant_id, 'NEGRO'),
    (v_tenant_id, 'ROJO'),
    (v_tenant_id, 'ROSA'),
    (v_tenant_id, 'AZUL'),
    (v_tenant_id, 'AZUL AQUA'),
    (v_tenant_id, 'AZUL MARINO'),
    (v_tenant_id, 'VERDE'),
    (v_tenant_id, 'MORADO'),
    (v_tenant_id, 'AMARILLO'),
    (v_tenant_id, 'LILA'),
    (v_tenant_id, 'FIUSHA'),
    (v_tenant_id, 'GRIS'),
    (v_tenant_id, 'COLORES')
  ON CONFLICT (tenant_id, nombre) DO NOTHING;

  -- -----------------------------------------------------------------------
  -- 4. Accesorios
  --    Para items sin color se usa 'SIN COLOR'.
  -- -----------------------------------------------------------------------
  INSERT INTO public.inv_accesorios
    (tenant_id, subcategoria_id, marca_id, color_id, codigo, nombre_producto, stock, precio)
  SELECT
    v_tenant_id,
    s.id,
    m.id,
    c.id,
    t.codigo,
    t.nombre_producto,
    t.stock,
    t.precio
  FROM (VALUES
    -- APPLE OEM
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10001', 'ADAPTADOR LIGHTNING A AUXILIAR',                                   7,   199),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10002', 'ADAPTADOR TIPO C A HEADPHONE JACK',                                7,   149),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10003', 'ADAPTADOR LIGHTNING A JACK',                                       7,   149),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10004', 'AIRPODS INALAMBRICOS 2DA GENERACION OEM',                          9,   389),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10005', 'AIRPODS INALAMBRICOS 3RA GENERACION OEM',                          9,   589),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10006', 'AIRPODS INALAMBRICOS PRO 2DA GENERACION OEM',                      9,   789),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10007', 'AIRPODS INALAMBRICOS 4TA GENERACION OEM',                          4,   989),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10008', 'BATTERY MAGSAFE IPHONE 5,000 MAH',                                 7,   389),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10009', 'BATTERY DUO MAGSAFE IPHONE',                                       3,   389),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10010', 'CABLE LIGHTNING A USB 1M',                                        21,   199),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10011', 'CABLE LIGHTHING A USB 2M',                                         9,   249),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10012', 'CABLE LIGHTNING A C 1M',                                          41,   199),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10013', 'CABLE LIGHTNING A C 2M',                                           9,   249),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10014', 'CABLE IPHONE C A C 1M',                                           21,   199),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10015', 'CABLE IPHONE C A C 2M',                                           11,   249),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10016', 'CABLE TIPO C A C - LIGHTNING 60W',                                12,   249),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10017', 'CARGADOR MAGSAFE IPHONE TIPO C',                                   9,   289),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10018', 'CARGADOR AUTO LIGHTHINIG A C',                                     6,   289),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10019', 'CARGADOR INALAMBRICO RELOJ IWATCH TIPO C',                         9,   289),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10020', 'CUBO IPHONE 5W A USB',                                             7,   149),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10021', 'CUBO IPAD 12W A USB',                                              6,   189),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10022', 'CUBO IPHONE 20W A TIPO C',                                        35,   289),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10023', 'CUBO IPHONE 35W TIPO C',                                          35,   389),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10024', 'CUBO IPHONE 60W A TIPO C',                                        11,   489),
    ('ACCESORIO OEM',              'APPLE',       'BLANCO',     'APPLE10025', 'EARPODS ALAMBRICOS ENTRADA LIGHTNING',                             7,   229),
    -- CHIPS / SIM
    ('TARJETA SIM',                'TELCEL',      'SIN COLOR',  'CHIPS10001', 'CHIP TELCEL 50 DISTRIBUIDOR FONIX',                               25,    50),
    ('TARJETA SIM',                'TELCEL',      'SIN COLOR',  'CHIPS10002', 'CHIP TELCEL 100 DISTRIBUIDOR FONIX',                              25,   100),
    ('TARJETA SIM',                'TELCEL',      'SIN COLOR',  'CHIPS10003', 'CHIP TELCEL 150 DISTRIBUIDOR FONIX MULTICHIP',                    25,   150),
    ('TARJETA SIM',                'TELCEL',      'SIN COLOR',  'CHIPS10004', 'CHIP TELCEL 50 DISTRIBUIDOR CELMI',                               25,    50),
    ('TARJETA SIM',                'TELCEL',      'SIN COLOR',  'CHIPS10005', 'CHIP TELCEL 100 DISTRIBUIDOR CELMI',                              25,   100),
    ('TARJETA SIM',                'TELCEL',      'SIN COLOR',  'CHIPS10006', 'CHIP TELCEL 150 DISTRIBUIDOR CELMI PLUS',                         20,   150),
    ('TARJETA SIM',                'UNEFON',      'SIN COLOR',  'CHIPS10007', 'CHIP UNEFON 50 DISTRIBUIDOR DICLINE',                             20,    50),
    ('TARJETA SIM',                'AT&T',        'SIN COLOR',  'CHIPS10008', 'CHIP AT&T 50 DISTRIBUIDORDICLINE',                                20,    50),
    ('TARJETA SIM',                'BIENESTAR',   'SIN COLOR',  'CHIPS10009', 'CHIP BIENESTAR DISTRIBUIDOR DALEFON',                             20,   100),
    ('TARJETA SIM',                'TELCEL',      'SIN COLOR',  'CHIPS10010', 'CHIP PORTABILIDAD TELCEL 100 DISTRIBUIDOR CELMI',                 15,   100),
    ('TARJETA SIM',                'BAIT',        'SIN COLOR',  'CHIPS10011', 'CHIP BAIT 50 DISTRIBUIDOR GRUPO SIM-A',                           20,    50),
    -- ESIM
    ('ESIM DIGITAL',               'TELCEL QR',   'SIN COLOR',  'CHIPS10012', 'ESIM DIGITAL TELCEL QR TODAS LAS LADAS (SERVERFULL) INSTANTE',    5,   380),
    ('ESIM DIGITAL',               'AT&T QR',     'SIN COLOR',  'CHIPS10013', 'ESIM DIGITAL AT&T TODAS LAS LADAS (DECLINE) INSTANTE',            5,   480),
    ('ESIM DIGITAL',               'UNEFON QR',   'SIN COLOR',  'CHIPS10014', 'ESIM DIGITAL UNEFON TODAS LAS LADAS (DECLINE) INSTANTE',          5,   480),
    ('ESIM DIGITAL',               'BAIT QR',     'SIN COLOR',  'CHIPS10015', 'ESIM DIGITAL BAIT TODAS LAS LADAS (SITIO WEB) INSTANTE',          5,   480),
    ('ESIM DIGITAL',               'MOVISTAR QR', 'SIN COLOR',  'CHIPS10016', 'ESIM DIGITAL MOVISTAR TODAS LAS LADAS (SERVERFULL) 2- 4 HORAS',   5,   380),
    -- HUAWEI OEM
    ('ACCESORIO OEM',              'HUAWEI',      'BLANCO',     'HUAWE10001', 'ADAPTADOR JACK 3.5MM A C HUAWEI',                                  4,    99),
    ('ACCESORIO OEM',              'HUAWEI',      'BLANCO',     'HUAWE10002', 'CABLE HUAWEI USB A V8',                                           12,    99),
    ('ACCESORIO OEM',              'HUAWEI',      'BLANCO',     'HUAWE10003', 'CABLE HUAWEI USB A C',                                            12,    99),
    ('ACCESORIO OEM',              'HUAWEI',      'BLANCO',     'HUAWE10004', 'CABLE ORIGINAL HUAWEI C A C',                                      5,   129),
    ('ACCESORIO OEM',              'HUAWEI',      'BLANCO',     'HUAWE10005', 'CUBO ORIGINAL HUAWEI 15W',                                        15,    99),
    ('ACCESORIO OEM',              'HUAWEI',      'BLANCO',     'HUAWE10006', 'SUPER CARGADOR HUAWEI C A C 30W',                                  6,   289),
    ('ACCESORIO OEM',              'HUAWEI',      'BLANCO',     'HUAWE10007', 'TURBO CARGADOR HUAWEI USB-V8 15W',                                 6,   189),
    ('ACCESORIO OEM',              'HUAWEI',      'BLANCO',     'HUAWE10008', 'TURBO CARGADOR HUAWEI USB- C 15W',                                 6,   189),
    -- KINGSTON / ADATA (memorias)
    ('MEMORIA DE ALMACENAMIENTO',  'KINGSTON',    'SIN COLOR',  'KINGS10001', 'MEMORIA SD KINGSTON 32GB',                                        12,   149),
    ('MEMORIA DE ALMACENAMIENTO',  'KINGSTON',    'SIN COLOR',  'KINGS10002', 'MEMORIA SD KINGSTON 64GB',                                        12,   189),
    ('MEMORIA DE ALMACENAMIENTO',  'KINGSTON',    'SIN COLOR',  'KINGS10003', 'MEMORIA SD KINGSTON 128GB',                                       12,   289),
    ('MEMORIA DE ALMACENAMIENTO',  'KINGSTON',    'SIN COLOR',  'KINGS10004', 'MEMORIA SD KINGSTON 256GB',                                        6,   589),
    ('MEMORIA DE ALMACENAMIENTO',  'KINGSTON',    'SIN COLOR',  'KINGS10005', 'MEMORIA SD KINGSTON 512GB',                                        3,   989),
    ('MEMORIA DE ALMACENAMIENTO',  'ADATA',       'SIN COLOR',  'ADATA10001', 'MEMORIA USB KINGSTON 32GB ADATA',                                 20,   149),
    ('MEMORIA DE ALMACENAMIENTO',  'KINGSTON',    'SIN COLOR',  'KINGS10006', 'MEMORIA USB KINGSTON 64GB',                                        8,   189),
    ('MEMORIA DE ALMACENAMIENTO',  'KINGSTON',    'SIN COLOR',  'KINGS10007', 'MEMORIA USB KINGSTON 128GB',                                       8,   249),
    ('MEMORIA DE ALMACENAMIENTO',  'KINGSTON',    'SIN COLOR',  'KINGS10008', 'MEMORIA USB KINGSTON 256GB',                                       4,   589),
    ('MEMORIA DE ALMACENAMIENTO',  'KINGSTON',    'SIN COLOR',  'KINGS10009', 'MEMORIA USB KINGSTON 512GB',                                       2,   989),
    -- LENOVO OEM
    ('ACCESORIO OEM',              'LENOVO',      'ROSA',       'LENOV10001', 'THINKPUNKS LP40 PRO BLUETOOTH ROSA',                               5,   349),
    ('ACCESORIO OEM',              'LENOVO',      'BLANCO',     'LENOV10002', 'THINKPUNKS LP40 PRO BLUETOOTH BLANCO',                             5,   349),
    ('ACCESORIO OEM',              'LENOVO',      'NEGRO',      'LENOV10003', 'THINKPUNKS LP40 PRO BLUETOOTH NEGRO',                              5,   349),
    ('ACCESORIO OEM',              'LENOVO',      'MORADO',     'LENOV10004', 'THINKPUNKS LP40 PRO BLUETOOTH MORADO',                             5,   349),
    ('ACCESORIO OEM',              'LENOVO',      'VERDE',      'LENOV10005', 'THINKPUNKS LP40 PRO BLUETOOTH VERDE',                              5,   349),
    -- LG OEM
    ('ACCESORIO OEM',              'LG',          'BLANCO',     'LG10000001', 'CABLE LG USB TIPO V8',                                            12,    99),
    ('ACCESORIO OEM',              'LG',          'BLANCO',     'LG10000002', 'CABLE LG USB TIPO C',                                             12,    99),
    ('ACCESORIO OEM',              'LG',          'BLANCO',     'LG10000003', 'TURBO CARGADOR LG 15W TIPO V8',                                    6,   189),
    ('ACCESORIO OEM',              'LG',          'BLANCO',     'LG10000004', 'TURBO CARGADOR LG 15W TIPO C',                                     6,   189),
    -- MOBO GENERICO
    ('ACCESORIO GENERICO',         'MOBO',        'BLANCO',     'MOBO100001', 'AUDIFONOS FLAT 3.5MM MOBO BLANCO',                                 8,   149),
    ('ACCESORIO GENERICO',         'MOBO',        'ROJO',       'MOBO100002', 'AUDIFONOS FLAT 3.5MM MOBO ROJO',                                   8,   149),
    ('ACCESORIO GENERICO',         'MOBO',        'NEGRO',      'MOBO100003', 'AUDIFONOS FLAT 3.5MM MOBO NEGRO',                                  8,   149),
    ('ACCESORIO GENERICO',         'MOBO',        'BLANCO',     'MOBO100004', 'CABLE AUXILIAR 1.2M MOBO',                                        12,    89),
    ('ACCESORIO GENERICO',         'MOBO',        'NEGRO',      'MOBO100005', 'CAMARA WEB HD MOBO',                                               6,   189),
    ('ACCESORIO GENERICO',         'MOBO',        'NEGRO',      'MOBO100006', 'CARGADOR TIPO V8 PARED 1A MOBO',                                  36,    69),
    ('ACCESORIO GENERICO',         'MOBO',        'NEGRO',      'MOBO100007', 'CARGADOR TIPO V8 CARRO 1A MOBO',                                  67,    69),
    ('ACCESORIO GENERICO',         'MOBO',        'NEGRO',      'MOBO100008', 'CARGADOR TIPO C PARED 1A MOBO',                                   23,    69),
    ('ACCESORIO GENERICO',         'MOBO',        'NEGRO',      'MOBO100009', 'CARGADOR TIPO IPHONE PARED 1A MOBO',                              38,    69),
    ('ACCESORIO GENERICO',         'MOBO',        'NEGRO',      'MOBO100010', 'CARGADOR TIPO V8 PARED 2A MOBO',                                   6,   129),
    ('ACCESORIO GENERICO',         'MOBO',        'NEGRO',      'MOBO100011', 'CARGADOR TIPO C PARED 2A MOBO',                                    3,   129),
    ('ACCESORIO GENERICO',         'MOBO',        'NEGRO',      'MOBO100012', 'CARGADOR TIPO IPHONE PARED 2A MOBO',                               2,   129),
    ('ACCESORIO GENERICO',         'MOBO',        'NEGRO',      'MOBO100013', 'MANOS LIBRES BLUETOOTH MOBO CONFORT',                              8,   189),
    -- MOREKA GENERICO
    ('ACCESORIO GENERICO',         'MOREKA',      'COLORES',    'MOREK10001', 'CABLE AUXILIAR COLORS 1.2M MOREKA',                               20,    45),
    ('ACCESORIO GENERICO',         'MOREKA',      'NEGRO',      'MOREK10002', 'BOCINA BLUETOOTH NEGRO MOREKA',                                    3,   199),
    ('ACCESORIO GENERICO',         'MOREKA',      'ROJO',       'MOREK10003', 'BOCINA BLUETOOTH ROJO MOREKA',                                     5,   199),
    ('ACCESORIO GENERICO',         'MOREKA',      'VERDE',      'MOREK10004', 'BOCINA BLUETOOTH VERDE MOREKA',                                    5,   199),
    ('ACCESORIO GENERICO',         'MOREKA',      'AZUL',       'MOREK10005', 'BOCINA BLUETOOTH AZUL MOREKA',                                     4,   199),
    -- MOTOROLA OEM
    ('ACCESORIO OEM',              'MOTOROLA',    'NEGRO',      'MOTOR10001', 'CABLE MOTOROLA USB - V8',                                         12,    99),
    ('ACCESORIO OEM',              'MOTOROLA',    'NEGRO',      'MOTOR10002', 'CABLE MOTOROLA USB - C',                                          12,    99),
    ('ACCESORIO OEM',              'MOTOROLA',    'NEGRO',      'MOTOR10003', 'CABLE MOTOROLA C A C',                                             9,   129),
    ('ACCESORIO OEM',              'MOTOROLA',    'NEGRO',      'MOTOR10004', 'CUBO USB MOTOROLA 15W',                                           12,    99),
    ('ACCESORIO OEM',              'MOTOROLA',    'NEGRO',      'MOTOR10005', 'SUPER CARGADOR MOTOROLA 30W C A C',                                9,   289),
    ('ACCESORIO OEM',              'MOTOROLA',    'NEGRO',      'MOTOR10006', 'TURBO CARGADOR MOTOROLA 15W TIPO V8',                              6,   189),
    ('ACCESORIO OEM',              'MOTOROLA',    'NEGRO',      'MOTOR10007', 'TURBO CARGADOR MOTOROLA 15W TIPO C',                               6,   189),
    ('ACCESORIO OEM',              'MOTOROLA',    'NEGRO',      'MOTOR10008', 'TURBO CARGADOR AUTO MOTOROLA 15W TIPO V8',                         5,   189),
    ('ACCESORIO OEM',              'MOTOROLA',    'NEGRO',      'MOTOR10009', 'TURBO CARGADOR AUTO MOTOROLA 15W TIPO C',                          5,   189),
    -- OPPO OEM
    ('ACCESORIO OEM',              'OPPO',        'BLANCO',     'OPPO100001', 'TURBO CARGADOR OPPO 15W TIPO V8',                                 13,   189),
    ('ACCESORIO OEM',              'OPPO',        'BLANCO',     'OPPO100002', 'TURBO CARGADOR OPPO 15W TIPO C',                                  13,   189),
    -- REALFIT OEM
    ('ACCESORIO OEM',              'REALFIT',     'MORADO',     'REALF10001', 'AUDIFONOS BLUETOOTH REALFIT F2 MORADO',                            3,   429),
    ('ACCESORIO OEM',              'REALFIT',     'NEGRO',      'REALF10002', 'AUDIFONOS BLUETOOTH REALFIT F2 NEGRO',                             3,   429),
    ('ACCESORIO OEM',              'REALFIT',     'ROSA',       'REALF10003', 'AUDIFONOS BLUETOOTH REALFIT F2 ROSA',                              3,   429),
    ('ACCESORIO OEM',              'REALFIT',     'BLANCO',     'REALF10004', 'AUDIFONOS BLUETOOTH REALFIT F2 BLANCO',                            3,   429),
    -- SAMSUNG OEM
    ('ACCESORIO OEM',              'SAMSUNG',     'BLANCO',     'SAMSU10001', 'ADAPTADOR SAMSUNG C TO AUXILIAR BLANCO',                           9,    99),
    ('ACCESORIO OEM',              'SAMSUNG',     'NEGRO',      'SAMSU10002', 'ADAPTADOR SAMSUNG C TO AUXILIAR NEGRO',                            9,    99),
    ('ACCESORIO OEM',              'SAMSUNG',     'NEGRO',      'SAMSU10003', 'AUDIFONOS AKG SAMSUNG 3.5MM NEGRO',                               10,    99),
    ('ACCESORIO OEM',              'SAMSUNG',     'BLANCO',     'SAMSU10004', 'AUDIFONOS AKG SAMSUNG C TO AUXILIAR BLANCO',                      10,   129),
    ('ACCESORIO OEM',              'SAMSUNG',     'NEGRO',      'SAMSU10005', 'AUDIFONOS AKG SAMSUNG C TO AUXILIAR NEGRO',                       10,   129),
    ('ACCESORIO OEM',              'SAMSUNG',     'BLANCO',     'SAMSU10006', 'CABLE USB SAMSUNG TIPO V8',                                       12,    99),
    ('ACCESORIO OEM',              'SAMSUNG',     'BLANCO',     'SAMSU10007', 'CABLE SAMSUNG TIPO C',                                            12,    99),
    ('ACCESORIO OEM',              'SAMSUNG',     'NEGRO',      'SAMSU10008', 'CABLE SAMSUNG C A C',                                             12,   129),
    ('ACCESORIO OEM',              'SAMSUNG',     'BLANCO',     'SAMSU10009', 'CARGADOR INALAMBRICO SAMSUNG BLANCO',                              2,   289),
    ('ACCESORIO OEM',              'SAMSUNG',     'NEGRO',      'SAMSU10010', 'CARGADOR INALAMBRICO SAMSUNG NEGRO',                               1,   289),
    ('ACCESORIO OEM',              'SAMSUNG',     'BLANCO',     'SAMSU10011', 'CUBO USB SAMSUNG 15W',                                            12,    99),
    ('ACCESORIO OEM',              'SAMSUNG',     'NEGRO',      'SAMSU10012', 'CUBO SAMSUNG C 25W',                                              11,   189),
    ('ACCESORIO OEM',              'SAMSUNG',     'NEGRO',      'SAMSU10013', 'CUBO SAMSUNG USB-C 45W',                                          11,   229),
    ('ACCESORIO OEM',              'SAMSUNG',     'NEGRO',      'SAMSU10014', 'SUPER CARGADOR SAMSUNG C A C 25W',                                16,   289),
    ('ACCESORIO OEM',              'SAMSUNG',     'NEGRO',      'SAMSU10015', 'SUPER CARGADOR SAMSUNG C A C 45W',                                11,   349),
    ('ACCESORIO OEM',              'SAMSUNG',     'NEGRO',      'SAMSU10016', 'TURBO CARGADOR SAMSUNG 15W TIPO C',                                6,   189),
    ('ACCESORIO OEM',              'SAMSUNG',     'BLANCO',     'SAMSU10017', 'TURBO CARGADOR AUTO SAMSUNG 15W TIPO V8',                          3,   189),
    ('ACCESORIO OEM',              'SAMSUNG',     'NEGRO',      'SAMSU10018', 'TURBO CARGADOR AUTO SAMSUNG 25W TIPO C',                           4,   289),
    ('ACCESORIO OEM',              'SAMSUNG',     'NEGRO',      'SAMSU10019', 'TURBO CARGADOR SAMSUNG 65W C A C',                                 7,   429),
    -- TWS F9 GENERICO
    ('ACCESORIO GENERICO',         'TWS F9',      'BLANCO',     'TWS1000001', 'AUDIFONOS BLUETOOTH TWS F9 BLANCO',                                3,   199),
    ('ACCESORIO GENERICO',         'TWS F9',      'NEGRO',      'TWS1000002', 'AUDIFONOS BLUETOOTH TWS F9 NEGRO',                                 0,   199),
    ('ACCESORIO GENERICO',         'TWS F9',      'AZUL',       'TWS1000003', 'AUDIFONOS BLUETOOTH TWS F9 AZUL',                                  6,   199),
    ('ACCESORIO GENERICO',         'TWS F9',      'MORADO',     'TWS1000004', 'AUDIFONOS B LUETOOTH TWS F9 MORADO',                               6,   199),
    ('ACCESORIO GENERICO',         'TWS F9',      'ROSA',       'TWS1000005', 'AUDIFONOS BLUETOOTH TWS F9 ROSA',                                  2,   199),
    ('ACCESORIO GENERICO',         'TWS F9',      'AMARILLO',   'TWS1000006', 'AUDIFONOS BLUETOOTH TWS F9 AMARILLO',                              7,   199),
    -- VARIOS GENERICO
    ('ACCESORIO GENERICO',         'VARIOS',      'SIN COLOR',  'VARIO10001', 'ADAPTADOR AUXILIAR A BLUETOOTH 89',                               12,    89),
    ('ACCESORIO GENERICO',         'VARIOS',      'SIN COLOR',  'VARIO10002', 'ADAPTADOR FM A BLUETOOTH 129',                                    11,   129),
    ('ACCESORIO GENERICO',         'VARIOS',      'SIN COLOR',  'VARIO10003', 'ADAPTADOR FM A BLUETOOTH 149',                                     9,   149),
    ('ACCESORIO GENERICO',         'VARIOS',      'SIN COLOR',  'VARIO10004', 'ADAPTADOR CLAVIJA EUROPEA A MX',                                  10,    39),
    ('ACCESORIO GENERICO',         'VARIOS',      'SIN COLOR',  'VARIO10005', 'ADAPTADOR FOR SD A USB',                                          19,    10),
    ('ACCESORIO GENERICO',         'VARIOS',      'SIN COLOR',  'VARIO10006', 'ADAPTADOR FOR SIM',                                               28,    10),
    ('ACCESORIO GENERICO',         'VARIOS',      'SIN COLOR',  'VARIO10007', 'ADAPTADOR JACK TO C',                                              2,    35),
    ('ACCESORIO GENERICO',         'VARIOS',      'SIN COLOR',  'VARIO10008', 'ADAPTADOR OTG V8',                                                30,    19),
    ('ACCESORIO GENERICO',         'VARIOS',      'SIN COLOR',  'VARIO10009', 'ADAPTADOR OTG C',                                                 10,    25),
    ('ACCESORIO GENERICO',         'VARIOS',      'SIN COLOR',  'VARIO10010', 'ANILLO SUJETADOR PARA CELULAR',                                    9,    15),
    ('ACCESORIO GENERICO',         'VARIOS',      'SIN COLOR',  'VARIO10011', 'KIT DE HERRAMIENTAS PARA CELULAR',                                30,    35),
    ('ACCESORIO GENERICO',         'LECTOR CLIP', 'SIN COLOR',  'VARIO10012', 'LECTOR DE TARJETA CLIP',                                           8,   189),
    ('ACCESORIO GENERICO',         'VARIOS',      'SIN COLOR',  'VARIO10013', 'MULTI-CABLE PULPO',                                               28,    49),
    ('ACCESORIO GENERICO',         'VARIOS',      'SIN COLOR',  'VARIO10014', 'MULTI-CARGADOR DE BATERIAS EXTERNAS',                             26,    35),
    ('ACCESORIO GENERICO',         'VARIOS',      'SIN COLOR',  'VARIO10015', 'SOPORTE DE CELULAR',                                               8,    35),
    -- XIAOMI OEM
    ('ACCESORIO OEM',              'XIAOMI',      'BLANCO',     'XIAOM10001', 'CABLE USB XIAOMI TIPO V8 OEM',                                    12,    99),
    ('ACCESORIO OEM',              'XIAOMI',      'BLANCO',     'XIAOM10002', 'CABLE USB XIAOMI TIPO C OEM',                                     12,    99),
    ('ACCESORIO OEM',              'XIAOMI',      'BLANCO',     'XIAOM10003', 'SUPER CARGADOR XIAOMI 67W TIPO C A C OEM',                         7,   349),
    ('ACCESORIO OEM',              'XIAOMI',      'BLANCO',     'XIAOM10004', 'SUPER CARGADOR XIAOMI 30W TIPO C A C OEM',                         6,   289),
    ('ACCESORIO OEM',              'XIAOMI',      'BLANCO',     'XIAOM10005', 'TURBO CARGADOR XIAOMI 15W TIPO V8 OEM',                            7,   189),
    ('ACCESORIO OEM',              'XIAOMI',      'BLANCO',     'XIAOM10006', 'TURBO CARGADOR XIAOMI 15W TIPO C OEM',                             7,   189),
    -- 1HORA GENERICO
    ('ACCESORIO GENERICO',         '1HORA',       'BLANCO',     '1HORA10001', 'AUDIFONO 3.5MM ECONOMICO 1HORA BLANCO AUT122',                    27,    35),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10002', 'AUDIFONO 3.5MM ECONOMICO NEGRO 1HORA AUT122',                     27,    35),
    ('ACCESORIO GENERICO',         '1HORA',       'LILA',       '1HORA10003', 'AUDIFONOS BLUETOOTH 1 HORA LILA AUT119',                           5,   289),
    ('ACCESORIO GENERICO',         '1HORA',       'ROSA',       '1HORA10004', 'AUDIFONOS BLUETOOTH 1 HORA ROSA AUT119',                           5,   289),
    ('ACCESORIO GENERICO',         '1HORA',       'AZUL AQUA',  '1HORA10005', 'AUDIFONOS BLUETOOTH 1 HORA AZUL AQUA AUT119',                      5,   289),
    ('ACCESORIO GENERICO',         '1HORA',       'MORADO',     '1HORA10006', 'AUDIFONOS BLUETOOTH 1 HORA MORADO AUT119',                         5,   289),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10007', 'AUDIFONOS BLUETOOTH 1 HORA NEGRO AUT119',                          5,   289),
    ('ACCESORIO GENERICO',         '1HORA',       'AZUL MARINO','1HORA10008', 'AUDIFONOS BLUETOOTH 1 HORA AZUL MARINO AUT119',                    5,   289),
    ('ACCESORIO GENERICO',         '1HORA',       'FIUSHA',     '1HORA10009', 'AUDIFONOS BLUETOOTH 1 HORA FIUSHA AUT119',                         5,   289),
    ('ACCESORIO GENERICO',         '1HORA',       'BLANCO',     '1HORA10010', 'AUDIFONOS BLUETOOTH 1 HORA BLANCO AUT119',                         5,   289),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10011', 'BAT.10,000MAH 1 HORA NEGRO LISA GAR130',                           3,   299),
    ('ACCESORIO GENERICO',         '1HORA',       'GRIS',       '1HORA10012', 'BAT.10,000MAH 1 HORA GRIS LISA GAR130',                            3,   299),
    ('ACCESORIO GENERICO',         '1HORA',       'AZUL',       '1HORA10013', 'BAT.10,000MAH 1 HORA AZUL LISA GAR130',                            3,   299),
    ('ACCESORIO GENERICO',         '1HORA',       'ROJO',       '1HORA10014', 'BAT.10,000MAH 1 HORA ROJO LISA GAR130',                            3,   299),
    ('ACCESORIO GENERICO',         '1HORA',       'ROJO',       '1HORA10015', 'BAT.10,000MAH 1HORA ROJA LISA GAR263',                             4,   399),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10016', 'BAT.10,000MAH 1HORA NEGRA ISA GAR263',                             4,   399),
    ('ACCESORIO GENERICO',         '1HORA',       'ROJO',       '1HORA10017', 'BAT. MULTICABLES 10,000MAH 1 HORA ROJO GAR148',                    4,   399),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10018', 'BAT. MULTICABLES 10,000MAH 1HORA NEGRO GAR148',                    4,   399),
    ('ACCESORIO GENERICO',         '1HORA',       'ROJO',       '1HORA10019', 'BAT. MULTICABLES 20,000MAH 1 HORA ROJO GAR159',                    4,   499),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10020', 'BAT. MULTICABLES 20,000MAH 1 HORA NEGRO GAR159',                   4,   499),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10021', 'BAT. LISA 20.000MAH 1HORA NEGRO GAR158',                           4,   499),
    ('ACCESORIO GENERICO',         '1HORA',       'BLANCO',     '1HORA10022', 'BAT. LISA 30,000MAH 1HORA BLANCO GAR138',                          4,   599),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10023', 'BOCINA BLUETOOTH BARRA 1 HORA BOC241',                             4,   389),
    ('ACCESORIO GENERICO',         '1HORA',       'ROJO',       '1HORA10024', 'BOCINA BLUETOOTH ROJO 1HORA BOC060',                               2,   199),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10025', 'CABLE TIPO V8 TO USB NEGRO 1 HORA CAB236',                        65,    45),
    ('ACCESORIO GENERICO',         '1HORA',       'BLANCO',     '1HORA10026', 'CABLE TIPO V8 TO USB BLANCO 1 HORA CAB236',                       65,    45),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10027', 'CABLE TIPO C TO USB NEGRO 1 HORA CAB237',                         65,    45),
    ('ACCESORIO GENERICO',         '1HORA',       'BLANCO',     '1HORA10028', 'CABLE TIPO C TO USB BLANCO 1 HORA CAB237',                        65,    45),
    ('ACCESORIO GENERICO',         '1HORA',       'BLANCO',     '1HORA10029', 'CABLE TIPO C TO C BLANCO 1HORA CAB252',                           25,    45),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10030', 'CABLE TIPO C TO C NEGRO 1HORA CAB252',                            25,    45),
    ('ACCESORIO GENERICO',         '1HORA',       'BLANCO',     '1HORA10031', 'CABLE IPHONE TO USB 1 HORA CAB238',                               45,    45),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10032', 'CABLE MULTI-ENTRADAS TO USB 1HORA CAB260',                        12,    69),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10033', 'CARGADOR INALAMBRICO 1HORA GAR151',                               12,   229),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10034', 'CARGADOR KIT COMPLETO 1 HORA V8 12W GAR124 NEGRO',                12,   149),
    ('ACCESORIO GENERICO',         '1HORA',       'BLANCO',     '1HORA10035', 'CARGADOR KIT COMPLETO 1 HORA V8 12W GAR124 BLANCO',               12,   149),
    ('ACCESORIO GENERICO',         '1HORA',       'BLANCO',     '1HORA10036', 'CARGADOR KIT COMPLETO 1 HORA IPHONE 12W GAR143 BLANCO',           12,   149),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10037', 'CARGADOR KIT COMPLETO 1 HORA TIPO C 20W GAR153 NEGRO',            16,   189),
    ('ACCESORIO GENERICO',         '1HORA',       'BLANCO',     '1HORA10038', 'CARGADOR KIT COMPLETO 1 HORA IPHONE 20W GAR154 BLANCO',           16,   189),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10039', 'CUBO USB NEGRO 1A 1HORA GAR063',                                  56,    25),
    ('ACCESORIO GENERICO',         '1HORA',       'BLANCO',     '1HORA10040', 'CUBO USB BLANCO 1A 1HORA GAR063',                                 45,    25),
    ('ACCESORIO GENERICO',         '1HORA',       'BLANCO',     '1HORA10041', 'CUBO USB BLANCO 2A 1 HORA GAR107 (EN CAJA)',                      20,    45),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10042', 'CUBO USB NEGRO 2A 1 HORA GAR107 (EN CAJA)',                       20,    45),
    ('ACCESORIO GENERICO',         '1HORA',       'BLANCO',     '1HORA10043', 'CUBO TURBO TIPO C 20W 1HORA GAR152',                              17,   129),
    ('ACCESORIO GENERICO',         '1HORA',       'NEGRO',      '1HORA10044', 'PLUG BALA AUTO NEGRO 1 HORA GAR101',                              18,    25),
    ('ACCESORIO GENERICO',         '1HORA',       'BLANCO',     '1HORA10045', 'PLUG BALA AUTO BLANCO 1 HORA GAR101',                             33,    25),
    ('ACCESORIO GENERICO',         '1HORA',       'BLANCO',     '1HORA10046', 'PLUG BALA AUTO BLANCO 1HORA EN CAJA GAR128 (EN CAJA)',            45,    45),
    ('ACCESORIO GENERICO',         '1HORA',       'SIN COLOR',  '1HORA10047', 'PILAS ALCALINAS AA 1 HORA GAR136',                                 5,    35),
    ('ACCESORIO GENERICO',         '1HORA',       'SIN COLOR',  '1HORA10048', 'SOPORTE PARA CELULAR 1HORA PJ098',                                12,    49),
    ('ACCESORIO GENERICO',         '1HORA',       'GRIS',       '1HORA10049', 'TURBO CARGADOR PARA AUTO TIPO C 1HORA GAR241',                    16,   189),
    -- LIBERADORES IPHONE
    ('LIBERADOR IPHONE',           'USIM',        'SIN COLOR',  'RUSIM10001', 'RSIM USIM LIBERACION SEMIPERMANENTE IPHONE',                      10,   580),
    ('LIBERADOR IPHONE',           'HEIDCARD',    'SIN COLOR',  'RHEIC10001', 'RSIM HEIDCARD LIBERACION SEMIPERMANENTE IPHONE',                  10,   580),
    ('LIBERADOR IPHONE',           'HEIDCARD',    'SIN COLOR',  'RHEIV10001', 'RSIM HEIDCARD LIBERACION SEMIPERMANENTE IPHONE VERIZON 12 HACIA ABAJO', 4, 580),
    -- VIDRIOS TEMPLADOS SAMSUNG
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VISAM10001', 'SAM. A01 VIDRIO BASICO',                                          16,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VISAM10002', 'SAM. A04 CORE BASICO',                                            25,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DSAM10001', 'SAM. A04 CORE 9D',                                                25,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRSAM10001', 'SAM. A04 CORE PRIVACIDAD',                                        25,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VISAM10003', 'SAM. J5-J500 BASICO',                                              7,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VISAM10004', 'SAM. J7-J700 BASICO',                                              8,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VISAM10005', 'SAM. J7 PRIME-G610 BASICO',                                       20,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VISAM10006', 'SAM. J7 PRO-J710 BASICO',                                         24,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VISAM10007', 'SAM. GRAND PRIME BASICO',                                         31,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VISAM10008', 'SAM. A21-A21S BASICO',                                            45,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DSAM10002', 'SAM. A21-A21S 9D',                                                25,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRSAM10002', 'SAM. A21-A21S PRIVACIDAD',                                        25,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VISAM10009', 'SAM. A50 BASICO',                                                 25,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DSAM10003', 'SAM. A50 9D',                                                     25,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRSAM10003', 'SAM. A50 PRIVACIDAD',                                             25,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VISAM10010', 'SAM. A54 BASICO',                                                 25,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DSAM10004', 'SAM. A54 9D',                                                     25,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRSAM10004', 'SAM. A54 PRIVACIDAD',                                             25,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VISAM10011', 'SAM. A70-A02-A03 BASICO',                                         45,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DSAM10005', 'SAM. A70-A02-A03 9D',                                             51,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRSAM10005', 'SAM. A70-A02-A03 PRIVACIDAD',                                     45,    99),
    -- VIDRIOS TEMPLADOS IPHONE
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10001', 'IPHONE 5G-5C-5S-5G BASICO',                                       17,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10002', 'IPHONE 6G-6S-7G-8G BASICO',                                       24,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10001', 'IPHONE 6G-6S-7G-8G 9D NEGRO',                                     26,    69),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10002', 'IPHONE 6G-6S-7G-8G 9D BLANCO',                                    19,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRIPH10001', 'IPHONE 6G-6S-7G-8G PRIVACIDAD',                                   15,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10003', 'IPHONE 6 PLUS-6S PLUS-7 PLUS-8 PLUS BASICO',                      19,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10003', 'IPHONE 6 PLUS-6S PLUS-7 PLUS-8 PLUS 9D NEGRO',                    22,    69),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10004', 'IPHONE 6 PLUS-6S PLUS-7 PLUS-8 PLUS 9D BLANCO',                   33,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRIPH10002', 'IPHONE 6 PLUS-6S PLUS-7 PLUS-8 PLUS PRIVACIDAD',                  14,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10004', 'IPHONE X-XS-11 PRO (5.8) BASICO',                                 25,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10005', 'IPHONE X-XS-11 PRO (5.8) 9D',                                     25,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRIPH10003', 'IPHONE X-XS-11 PRO (5.8) PRIVACIDAD',                             25,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10005', 'IPHONE XS MAX-11 PRO MAX (6.5) BASICO',                           25,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10006', 'IPHONE XS MAX-11 PRO MAX (6.5) 9D',                               25,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRIPH10004', 'IPHONE XS MAX-11 PRO MAX (6.5) PRIVACIDAD',                       25,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10006', 'IPHONE XR-11 BASICO',                                             25,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10007', 'IPHONE XR-11 9D',                                                 25,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRIPH10005', 'IPHONE XR-11 PRIVACIDAD',                                         25,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10007', 'IPHONE 12 MINI-13 MINI BASICO',                                   53,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10008', 'IPHONE 12 MINI-13 MINI 9D',                                       31,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRIPH10006', 'IPHONE 12 MINI-13 MINI PRIVACIDAD',                               24,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10008', 'IPHONE 12-12 PRO BASICO',                                         33,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10009', 'IPHONE 12-12 PRO 9D',                                             22,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRIPH10007', 'IPHONE 12-12 PRO PRIVACIDAD',                                     20,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10009', 'IPHONE 12 PRO MAX BASICO',                                        45,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10010', 'IPHONE 12 PRO MAX 9D',                                            23,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRIPH10008', 'IPHONE 12 PRO MAX PRIVACIDAD',                                    30,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10010', 'IPHONE 13-13 PRO -14 - 16E BASICO',                               41,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10011', 'IPHONE 13-13 PRO -14-16E 9D',                                     38,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRIPH10009', 'IPHONE 13-13 PRO -14 PRIVACIDAD',                                 41,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10011', 'IPHONE 13 PRO MAX -14 PLUS BASICO',                               46,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10012', 'IPHONE 13 PRO MAX -14 PLUS 9D',                                   23,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRIPH10010', 'IPHONE 13 PRO MAX -14 PLUS PRIVACIDAD',                           32,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10012', 'IPHONE 14 PRO BASICO',                                            47,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10013', 'IPHONE 14 PRO 9D',                                                23,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRIPH10011', 'IPHONE 14 PRO PRIVACIDAD',                                        20,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10013', 'IPHONE 14 PRO MAX BASICO',                                        21,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10014', 'IPHONE 14 PRO MAX 9D',                                            20,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRIPH10012', 'IPHONE 14 PRO MAX PRIVACIDAD',                                    22,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10014', 'IPHONE 15-15 PRO - 16 BASICO',                                    29,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10015', 'IPHONE 15-15 PRO- 16 9D',                                         27,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRIPH10013', 'IPHONE 15-15 PRO - 16PRIVACIDAD',                                 29,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10015', 'IPHONE 15 PRO MAX-15 PLUS - 16 PLUS BASICO',                      41,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10016', 'IPHONE 15 PRO MAX-15 PLUS - 16 PLUS 9D',                          29,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRIPH10014', 'IPHONE 15 PRO MAX-15 PLUS-16 PLUS PRIVACIDAD',                    33,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10016A','IPHONE 16 PRO / 17 / 17 PRO BASICO',                              40,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10017A','IPHONE 16 PRO / 17 / 17 PRO 9D',                                  40,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRIPH10015A','IPHONE 16 PRO / 17 / 17 PRO PRIVACIDAD',                          40,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10016B','IPHONE 16 PRO MAX / 17 PRO MAX BASICO',                           40,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10017B','IPHONE 16 PRO MAX / 17 PRO MAX 9D',                               30,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRIPH10015B','IPHONE 16 PRO MAX / 17 PRO MAX PRIVACIDAD',                       35,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIIPH10016C','IPHONE 17 AIR BASICO',                                            20,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DIPH10017C','IPHONE 17 AIR 9D',                                                20,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRIPH10015C','IPHONE 17 AIR PRIVACIDAD',                                        20,    99),
    -- VIDRIOS TEMPLADOS UNIVERSALES
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIUNI10001', 'UNIVERSAL 4.0 BASICO',                                            18,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIUNI10002', 'UNIVERSAL 4.5 BASICO',                                            25,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIUNI10003', 'UNIVERSAL 5.0 BASICO',                                            25,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIUNI10004', 'UNIVERSAL 5.3 BASICO',                                            32,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIUNI10005', 'UNIVERSAL 5.5 BASICO',                                            20,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIUNI10006', 'UNIVERSAL 6.0 BASICO',                                            25,    25),
    -- VIDRIOS TEMPLADOS HUAWEI
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIHUA10001', 'HUAWEI Y9 PRIME-Y9S-STK LX3 BASICO',                              91,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DHUA10001', 'HUAWEI Y9 PRIME-Y9S-STK LX3 9D',                                  32,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRHUA10001', 'HUAWEI Y9 PRIME-Y9S-STK LX3 PRIVACIDAD',                          33,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIHUA10002', 'HUAWEI Y9 2019-Y8S-JKM LX3 BASICO',                              20,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DHUA10002', 'HUAWEI Y9 2019-Y8S-JKM LX3 9D',                                   25,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRHUA10002', 'HUAWEI Y9 2019-Y8S-JKM LX3 PRIVACIDAD',                           21,    99),
    -- VIDRIOS TEMPLADOS MOTOROLA
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIMOT10001', 'MOTO G5 BASICO',                                                  16,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIMOT10002', 'MOTO G5 PLUS BASICO',                                             18,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIMOT10003', 'MOTO G6 BASICO',                                                  14,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIMOT10004', 'MOTO G6 PLAY- E5 BASICO',                                         21,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIMOT10005', 'MOTO G6 PLUS BASICO',                                             16,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIMOT10006', 'MOTO G7 PLAY BASICO',                                             25,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIMOT10007', 'MOTO G9 POWER BASICO',                                            22,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DMOT10001', 'MOTO G9 POWER 9D',                                                15,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRMOT10001', 'MOTO G9 POWER PRIVACIDAD',                                        23,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIMOT10008', 'MOTO G9 PLUS BASICO',                                             13,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIMOT10009', 'MOTO G51 5G-G60-G60S-G40-G200 5G BASICO',                         33,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DMOT10002', 'MOTO G51 5G-G60-G60S-G40-G200 5G 9D',                             28,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRMOT10002', 'MOTO G51 5G-G60-G60S-G4O-G200 5G PRIVACIDAD',                     35,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIMOT10010', 'MOTO C-C PLUS BASICO',                                             5,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIMOT10011', 'MOTO E4 BASICO',                                                  19,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIMOT10012', 'MOTO E5 PLUS BASICO',                                             14,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIMOT10013', 'MOTO E6 BASICO',                                                  17,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIMOT10014', 'MOTO E6 PLUS-E6S 2020 BASICO',                                    30,    25),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIMOT10015', 'MOTO G23 BASICO',                                                 43,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DMOT10003', 'MOTO G23 9D',                                                     26,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PRMOT10003', 'MOTO G23 PRIVACIDAD',                                             25,    99),
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIMOT10016', 'MOTO ONE BASICO',                                                 12,    25),
    -- VIDRIOS TEMPLADOS OPPO
    ('VIDRIO TEMPLADO BASICO',     'DRAGON',      'SIN COLOR',  'VIOPP10001', 'OPPO A53-A54 BASICO',                                             51,    25),
    ('VIDRIO TEMPLADO 9D',         'DRAGON',      'SIN COLOR',  '9DOPP10001', 'OPPO A53-A54 9D',                                                 15,    69),
    ('VIDRIO TEMPLADO PRIVACIDAD', 'DRAGON',      'SIN COLOR',  'PROPP10001', 'OPPO A53-A54 PRIVACIDAD',                                         25,    99),
    -- LIQUIDACION MICA CERAMICA
    ('ACCESORIO GENERICO',         'GENGXIN',     'SIN COLOR',  'LIQVI10001', 'LIQUIDACION DE MICA CERAMICA VARIOS',                             89,    10),
    -- LAMINAS HIDROGEL
    ('LAMINA DE HIDROGEL',         'DRAGON',      'SIN COLOR',  'HIDRO10001', 'LAMINA HIDROGEL HD PLUS PARA CELULAR',                           150,   149),
    ('LAMINA DE HIDROGEL',         'DRAGON',      'SIN COLOR',  'HIDRO10002', 'LAMINA HIDROGEL HD PRIVACIDAD PARA CELULAR',                     150,   189),
    ('LAMINA DE HIDROGEL',         'DRAGON',      'SIN COLOR',  'HIDRO10003', 'LAMINA HIDROGEL HD PLUS PARA TABLET',                             25,   189),
    ('LAMINA DE HIDROGEL',         'DRAGON',      'SIN COLOR',  'HIDRO10004', 'LAMINA HIDROGEL HD DISENO',                                       50,   149),
    -- CELULAR DE USO
    ('CELULAR DE USO',             'ZTE',         'AZUL MARINO','PHONE10002', 'ZTE AXON V60 (86588107087633601)',                                  1,  1780)
  ) AS t(subcategoria, marca, color, codigo, nombre_producto, stock, precio)
  JOIN public.subcategorias s
    ON s.tenant_id = v_tenant_id AND s.nombre = t.subcategoria
  JOIN public.marcas m
    ON m.tenant_id = v_tenant_id AND m.nombre = t.marca
  JOIN public.colores c
    ON c.tenant_id = v_tenant_id AND c.nombre = t.color
  ON CONFLICT DO NOTHING;

END $$;
